apiVersion: v1
kind: Service
metadata:
  labels:
    name: cc-db
  name: cc-db
  namespace: openfaas-fn
spec:
  ports: 
  - port: 3306
    name: cc-db
    protocol: TCP
    targetPort: 3306
  #clusterIP: None
  selector:
    app: cc-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-db
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cc-db
    spec:
      hostname: cc-db
      containers:
      - image: jjhwan7099/cc-db:latest
        name: cc-db
        args: ["--init-file","/data/application/init.sql"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        - name: MYSQL_ROOT_USER
          value: root
        ports:
        - containerPort: 3306
          name: cc-db
